label final:
    scene cg2_1 with Dissolve(3)
    stop music
    play music reflect

    yume_th "นี่มัน..."
    yume_en "This is..."

    th "เราไม่อยากเชื่อสายตาของตัวเอง"
    en "I couldn’t believe my own eyes."
    th "ใบหน้าของคนคนหนึ่งจ้องมองกลับมาที่เรา"
    en "The face of someone stared back at me."
    th "หญิงสาวเรือนผมสีดำถลึงมองเราด้วยดวงตาคู่โตของเธอ"
    en "A woman with long black hair and large eyes gazed at me intently."
    th "ความคุ้นเคยนี่มัน..."
    en "This familiarity..."
    th "ไม่สิ"
    en "No"
    th "นี่ไม่ใช่แค่ความคุ้นเคย"
    en "it’s more than that."
    th "มันไม่ใช่แค่นั้น"
    en "It’s not just familiarity."
    th "....."
    en "....."
    th "มันคือ ความจริง"
    en "It’s the ‘truth’."
    th "มนุษย์ไม่สามารถหลีกหนีจากความจริงได้ตลอดไป"
    en "Humans can't escape the truth forever."
    th "....."
    en "....."
    th "สิ่งที่ปรากฏตรงหน้าเราคือกระจกบานใหญ่"
    en "What appeared before me was a large mirror."
    th "ภาพที่เราเห็นตอนนี้คือ...ใบหน้าที่แท้จริงของเรา..."
    en "The reflection I saw now... was my true face..."

    yume_th "...ผู้หญิง?"
    yume_en "...A woman?"
    scene cg2_2 with dissolve

    th "เรามั่นใจว่าคนในความทรงจำที่เราคุยด้วยคือผู้หญิง"
    en "I was sure the person in my memories I talked with was a woman."
    th "...แต่ตัวเรา...?"
    en  "...But me...?"
    th "เราก็เป็นผู้หญิงด้วยเหรอ"
    en "Am I also a woman?"
    th "ความรู้สึกผูกพันและโหยหาที่เรามีต่อเธอคนนั้น"
    en "The feelings of connection and longing I had for her..."
    th "...รอยจูบที่เธอคนนั้นฝากไว้ให้..."
    en "...The kiss she left me..."
    th "นั่นหมายความว่า..."
    en "That means..."

    yume_th "...อึก!!"
    yume_en "...Uh!!"

    th "ความรู้สึกเจ็บแทรกผ่านเข้ามาในศีรษะ"
    en "Pain pierced through my head."
    th "ความทรมานราวกับถูกมีดฉีกทึ้งข้างในกะโหลกเกิดขึ้นซ้ำแล้วซ้ำเล่า...ซ้ำแล้วซ้ำเล่า..."
    en "It felt like a knife repeatedly tearing inside my skull... over and over..."
    th "ภาพสะท้อนในกระจกคือหญิงสาวที่กำลังส่งเสียงกรีดร้อง"
    en "The reflection in the mirror was a woman screaming."
    th "ใบหน้าของเธอคนนั้นบิดเบี้ยวไปด้วยความเจ็บปวด ก่อนที่เธอจะทรุดเข่าลง"
    en "Her face contorted in agony before she collapsed to her knees."

    scene black with Dissolve(1)

    th "ภาพตรงหน้าค่อยๆจมลงสู่สีดำ"
    en "The image before me slowly sunk into darkness."
    th "ใบหน้าในกระจกนั้นไม่ใช่ใครอื่น นอกจากเงาสะท้อนของตัวเราเอง"
    en "The face in the mirror was no one else but a reflection of myself."

    scene black with dissolve
    stop music
    play music 憂鬱

    th "ภาพความทรงจำทุกอย่างกำลังตีกลับมา"
    en "Every memory is forcefully resurfacing."
    th "สิ่งที่ทำให้มีความสุข สิ่งที่ทำให้จมอยู่ในความทุกข์ สิ่งที่ไม่อยากนึกถึงค่อยๆปรากฏขึ้น"
    en "The things that brought joy, the things that submerged me in sorrow, and the things I'd rather not remember are slowly emerging."
    th "ใช่แล้ว"
    en "Yes"
    th "...ชื่อของเราคือ ยูเมะ..."
    en "my name is 'Yume'..."

    scene sky_cloudy with dissolve

    th "เท่าที่เราจำความได้ ชีวิตวัยเด็กของเราไม่ใช่เรื่องดีเท่าไหร่นัก"
    en "As far as I can remember, my childhood was not a happy one."
    th "ครอบครัวของเรามีแต่ความขัดแย้งกัน ทุกวันๆเต็มไปด้วยการทะเลาะเบาะแว้งเรื่องหนี้สินและการแบ่งมรดกระหว่างตระกูลฝั่งพ่อและฝั่งแม่"
    en "My family was rife with conflict, every day filled with arguments over debts and the division of inheritance between my father's and mother's sides of the family."
    th "เราไม่ค่อยรู้รายละเอียดของเรื่องเงินทองเพราะตอนนั้นเรายังเด็กมาก"
    en " I didn't understand the details of the financial issues because I was very young."
    th "สิ่งที่เราจำได้ไม่มีวันลืมคือ แม่ของเราเป็นฆาตกร"
    en "What I can never forget is that 'my mother was a murderer"
    th "....."
    en "....."
    scene kitchen03 with dissolve
    th "แม่ทะเลาะกับญาติฝั่งพ่อที่เป็นผู้อาวุโสคนหนึ่งซึ่งเป็นที่นับหน้าถือตากันในหมู่บ้าน"
    en "My mother quarreled with a paternal relative, a respected elder in the village."
    th "ปัญหาที่ทะเลาะกันก็เป็นเรื่องมรดกเงินทองไม่ต่างจากเดิม แต่เพราะโทสะบังตาและถูกต้อนจนมุม แม่ของเราจึงระเบิดอารมณ์ใส่ญาติคนนั้น"
    en "The issue was the same as always - inheritance and money. Blinded by rage and pushed into a corner, my mother lashed out at that relative."
    th "เราในตอนเด็กไม่สามารถห้ามแม่เอาไว้ได้"
    en "As a child, I was powerless to stop her."
    th "เราที่ไร้พลังได้แต่ยืนมองแม่แท้ๆใช้มือบีบคอญาติคนนั้นจนตาย"
    en "Helplessly, I watched as my very own mother strangled that relative to death."

    th "....."

    th "หลังจากนั้นไม่นาน แม่ก็ถูกจับเข้าเรือนจำ"
    en "Not long after, my mother was arrested and imprisoned."
    th "ข่าวการเป็นฆาตกรของแม่แพร่สะพัดไปอย่างรวดเร็ว"
    en "The news of her being a murderer spread quickly."
    th "ญาติที่แม่เราฆ่าเป็นที่เป็นนับหน้าถือตาในชุมชน จึงไม่ใช่เรื่องแปลกที่จะข้อมูลจะจะถูกรู้อย่างทั่วถึงในเวลาไม่กี่วัน"
    en "The relative she killed was highly regarded in the community, so it was not surprising that the information was widely known within a few days."
    th "แน่นอนว่ามันมีผลมาถึงชีวิตในโรงเรียนของเราด้วย"
    en "Naturally. this had a profound impact on my life at school..."
    th "....."
    en "....."

    stop music
    play music 哀愁漂うホラー的な
    scene classroom_sunset with dissolve
    th "เราถูกคนในห้องเรียนมองว่าเป็นลูกของฆาตกร ทำให้เพื่อนๆตีตัวออกห่างจากเราทีละคนๆ"
    en "In the classroom, I was seen as the child of a murderer, causing my classmates to distance themselves from me one by one."
    th "ชีวิตในโรงเรียนที่เคยสงบสุขพังทลายลงเพราะบาปที่เราไม่ได้ก่อ"
    en "My once peaceful school life shattered due to a sin I did not commit."
    th "ท้ายที่สุดเราก็ไม่เหลือใครอยู่เลยนอกจากคนที่คอยรังแกเรา"
    en "Eventually, I was left with no one but those who enjoyed bullying me."
    th "อย่างไรก็ตาม เราไม่ได้สนใจจะเป็นเพื่อนกับคนพวกนั้นอยู่แล้ว"
    en " However, I never cared to befriend such people."
    th "คนที่ตัดสินคนอื่นจากบาปของคนในสายเลือดมีแต่พวกชั้นต่ำเท่านั้น"
    en "Only the lowly judge others based on the sins of their bloodline."
    th "ถ้าต้องฝืนคบหากับคนพวกนั้น เอาเวลาไปสนิทกับแมวข้างบ้านยังจะมีประโยชน์ซะกว่า"
    en " If I had to force myself to associate with them, I'd rather spend time with the neighborhood cat it would be more worthwhile."

    yume_th "ไม่รู้จักเปลี่ยนมุกเลยนะ เจ้าพวกบ้านั่น"
    yume_en "Can't they come up with anything new, those fools?"

    th "เราถอนใจพร้อมกับใช้ผ้าขาวชุบน้ำขัดโต๊ะเรียนหนังสือ"
    en "I sighed, wiping the desk with a wet cloth."
    th "การถูกใครก็ไม่รู้เขียนข้อความด่าทอว่าเป็นลูกของฆาตกรเป็นเรื่องที่เราโดนไม่รู้กี่สิบครั้งแล้ว"
    en " Being called the child of a murderer was something I had endured countless times."
    th "ครั้งแรกๆที่โดนก็เสียใจอยู่หรอก แต่พอโดนบ่อยๆก็ชินชาจนเผลอเตรียมชุดทำความสะอาดมาโรงเรียนมาขัดโต๊ะบ่อยๆ"
    en " It hurt at first, but repeated offenses made me numb, to the point where I habitually brought cleaning supplies to school to scrub off the hateful messages."
    th "พรุ่งนี้จะเป็นอะไรอีกนะ? โดนเอาของไปซ่อนหรือว่าโดนโยนขยะใส่กัน?"
    en "What will it be tomorrow? Will they hide my things or throw trash at me?"

    yume_th "เฮ้อ..."
    yume_en "Sigh..."

    th "คนพวกนี้คิดว่าการรังแกคนที่ตัวเองคิดว่าผิดทำให้ตัวเองเป็นฝ่ายที่ถูกต้องหรือไงกัน?"
    en "Do these people think bullying someone they deem wrong makes them right?"
    th "โง่เง่าชะมัดยาด"
    en "Such idiocy..."

    th "ไอ้ลูกฆาตกร"
    en "Murderer's kid."
    yume_th "เฮ้อ..."
    yume_en "..."
    th "คำพูดของคนที่ด่าทอเราดังขึ้นในศีรษะ" 
    en "Those words echoed in my head."
    th "เสียงจากความทรงจำที่ไม่อยากนึกถึงทำให้เรารู้สึกเดือดดาลขึ้นมา"
    en "a memory I'd rather forget, igniting a burning anger within me."
    th "...พวกน่ารังเกียจ...ต่อให้ไม่ตอบโต้หรือทำเป็นไม่สนใจก็จะโดนรังแกอยู่ดี..."
    en " ...Disgusting people... Even if I don't retaliate or ignore them, the bullying continues..."
    th "ความอดทนของเราไม่มีความหมายแม้แต่นิดเดียว"
    en "My patience means nothing."
    th "...หรือว่า...การใช้กำลังจะเป็นทางที่ดีกว่ากันนะ...?"
    en "...Maybe... using force would be a better way...?"

    yume_th "...ฮึ"
    yume_en "...Hmph."

    th "เราแค่นเสียงในลำคอเบาๆ"
    en "I chuckled softly to myself."
    th "...บางทีสิ่งที่แม่ทำอาจจะเป็นสิ่งที่ถูกต้อง..."
    en "...Maybe what my mother did was right..."
    th "ถ้าพวกมันไม่คิดจะฟังเรา พวกมันก็ไม่ควรมีโอกาสได้ฟังอีกต่อไป"
    en "If they refuse to listen to me, they don't deserve the chance to hear anything ever again."
    th "...ถูกแล้ว..."
    en "...That's right..."
    th "...ปล่อยตัวเองไปตามสัญชาตญาณสิ..."
    en "...Let yourself go with your instincts..."

    yume_th "ชิ"
    yume_en "Tch."

    th "เราทุบโต๊ะเบาๆด้วยความไม่สบอารมณ์"
    en "I tapped the desk lightly, annoyed."
    
    th "ความรู้สึกชั่ววูบเมื่อครู่ทำให้เราขยะแขยงตัวเองขึ้นมา"
    en "The fleeting malicious thought disgusted me."
    th "...ไม่...เราจะไม่ทำตัวอย่างผู้ใหญ่พวกนั้น"
    en "...No... I won't become like those adults."
    th "เราน่ะ..."
    en "I am..."
    th "เรา..."
    en 'I am...'

    stop music
    play music 泣カナイデ

    voice "audio/voice/final/mary_10_000.mp3"
    mary0_th "ถ้าขัดตรงที่สะอาดหมดแล้วซ้ำๆ มันจะไม่เสร็จสักทีนะ"
    yume_th  "หืม?"
    th "ขณะที่ความคิดของเราดำดิ่งสู่ความมืด เสียงกังวานใสเสียงหนึ่งก็ดังขึ้น"
    th "เวลานี้เป็นเวลาหลังเลิกเรียน นักเรียนคนอื่นน่าจะกลับบ้านกันหมดแล้ว แต่เด็กสาวผมทองในชุดนักเรียนชั้นปีเดียวกับเรากลับยืนมองเราด้วยสายตาสนอกสนใจ"
    en "In the classroom, as my thoughts plunged into darkness, a clear, resonant voice interrupted. It was after school hours, and other students should have been long gone, but there stood a blond-haired girl in the same year as me, looking at me with curious eyes."
    yume_th  "เธอเป็นใคร?"
    yume_en "Who are you?"
    th "ดวงตาคู่โตของเด็กสาวผมทองเบิกกว้างขึ้นน้อยๆ"
    en  "The girl with large eyes seemed surprised by my question."
    th "เธอดูประหลาดใจกับคำถามของเรา"
    en ""
    voice "audio/voice/final/mary_10_001.mp3"
    mary0_th "แมรี่ไงจ้ะ"
    mary0_en "It's Mary."
    yume_th "แมรี่?"
    yume_en "Mary?"
    voice "audio/voice/final/mary_10_002.mp3"
    mary_th "โธ่ ฉันเป็นนักเรียนแลกเปลี่ยนที่เข้ามาใหม่วันนี้ไงล่ะ"
    mary_en "Oh, come on. I'm the new exchange student who joined today."
    th "เด็กสาวผมทองที่ชื่อแมรี่ทำแก้มป่องน้อยๆ"
    en "Mary, the blond-haired girl, puffed her cheeks slightly."
    th "ทั้งๆที่เป็นคนแปลกหน้ากัน แต่ทำไมคนๆนี้ถึงเข้ามาใกล้เราขนาดนี้กันนะ"
    en "It was strange that a complete stranger would come so close to me."
    th "พิลึกคนจริงๆ"
    en "Very peculiar indeed."
    yume_th  "เธอจะเอาผ้ามาทำไม?"
    yume_en "Why did you bring a cloth?"
    voice "audio/voice/final/mary_10_003.mp3"
    mary_th "มาช่วยเธอขัดโต๊ะไงจ้ะ"
    mary_en "To help you clean the desk."
    th "เราทำตาปริบๆใส่แมรี่ด้วยความไม่เข้าใจ"
    en "I looked at Mary, puzzled."
    th "คนๆนี้จะได้อะไรจากการช่วยเรากัน"
    en "What would this person gain from helping me?"
    yume_th "ขอบคุณสำหรับความหวังดี" 
    yume_en "Thanks for the goodwill."
    voice "audio/voice/final/mary_10_004.mp3"
    mary_th "จ้ะ"
    mary_en "You're welcome."
    yume_th "แต่ถ้ามาช่วยฉัน เธอจะโดนคนอื่นรังแกไปด้วยนะ"
    yume_en "But if you help me, you'll get bullied too."
    
    mary_th "....."
    mary_en "....."
    th "เราพูดความจริงต่อหน้าเด็กสาวผมทอง"
    en "I told the truth to the blond-haired girl."
    th "ทั้งๆที่เราพูดเพื่อจะกันเธอออกไป แต่แมรี่กลับยื่นผ้ามาเช็ดโต๊ะให้เราพร้อมกับยิ้มบางๆออกมา"
    en "Although I spoke to push her away, Mary handed me the cloth and smiled faintly."
    yume_th "ทำไม?"
    yume_en "Why?"
    voice "audio/voice/final/mary_10_005.mp3"
    mary_th "หา?"
    mary_en "Huh?"
    yume_th "ทำไมถึงช่วยฉันล่ะ?"
    yume_en "Why help me?"
    voice "audio/voice/final/mary_10_007.mp3"
    mary_th "เธอรู้ไหมว่าเธอเป็นคนอ่อนโยนกว่าเธอคิดนะ"
    mary_en "Did you know you're kinder than you think?"
    th "แมรี่ตอบไม่ตรงคำถาม ทำให้เราเลิกคิ้วขึ้นด้วยความประหลาดใจ"
    en "Mary's response, not directly answering my question, made me raise my eyebrows in surprise."
    voice "audio/voice/final/mary_10_008.mp3"
    mary_th "เธอจะไล่ตะเพิดหรือมองข้ามฉันก็ได้ แต่เธอเลือกที่จะเตือนฉันดีๆเพราะเป็นห่วงฉัน"
    mary_en "You could have ignored or shooed me away, but you chose to warn me because you care."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_009.mp3"
    mary_th "ขนาดเราไม่ค่อยรู้จักกัน เธอยังคิดถึงฉันขนาดนี้ ถ้าไม่ใช่คนอ่อนโยนแล้วจะเรียกว่าอะไรดีล่ะจ้ะ?"
    mary_en "Even though we hardly know each other, you still think about me. If that's not kindness, then what is?"
    th "เด็กสาวผมทองส่งยิ้มกว้างกว่าเดิมให้เรา คำตอบของเธอทำให้เรารู้สึกสับสนอย่างบอกไม่ถูก"
    en "Mary's broad smile confused me further. Her response left me at a loss for words."
    yume_th "พิลึกคนชะมัด"
    yume_en "Peculiar person."
    voice "audio/voice/final/mary_10_010.mp3"
    mary_th "คนอื่นก็ชอบบอกแบบนั้นล่ะจ้ะ"
    mary_en "Others say that too."
    yume_th "ฮึๆๆ"
    yume_en "Heh..."
    th "เราส่งเสียงหัวเราะในลำคอเบาๆ"
    en "I chuckled softly."
    th "ตั้งแต่เมื่อไหร่กันนะที่เราไม่ได้หัวเราะให้คนอื่นเห็น น่าจะหลายปีพอสมควรเลย"
    en "When was the last time I laughed in front of someone else? It must have been years."
    voice "audio/voice/final/mary_10_011.mp3"
    mary_th "เธอชื่ออะไรเหรอจ้ะ?"
    mary_en "What's your name?"
    yume_th "จะอยากรู้ชื่อตัวปัญหาประจำชั้นเรียนทำไมกัน?"
    yume_en "Why would you want to know the name of the class's problem child?"
    voice "audio/voice/final/mary_10_012.mp3"
    mary_th "อยากรู้น่ะ ไม่ต้องมีเหตุผลหรอกจ้ะ"
    mary_en "I'm just curious. No reason needed."
    th "แมรี่หัวเราะให้เราบ้าง" 
    en "Mary laughed at me."
    th "ช่างเป็นผู้หญิงที่แปลกประหลาดจริงๆ"
    en "She was indeed a strange woman."
    yume_th "ฉันชื่อยูเมะ"
    yume_en "I'm Yume."
    voice "audio/voice/final/mary_10_013.mp3"
    mary_th "ชื่อน่ารักดีนะ ไม่เข้ากับหน้าตาเลยจ้ะ"
    mary_en "Cute name. Doesn't match your face."
    yume_th "เดี๋ยว?"
    yume_en "Excuse me?"
    voice "audio/voice/final/mary_10_014.mp3"
    mary_th "ล้อเล่นจ้ะๆ...ฝากตัวด้วยนะ ยูเมะ..."
    mary_en "Just kidding... Please take care of me, Yume..."
    yume_th "อืม"
    yume_en "Hmm."
    th "เราพยักหน้าให้เด็กสาวผมทองเบาๆ"
    en "I nodded slightly to the blond-haired girl."

    scene sky_cloudy with dissolve
    stop music
    play music up_to_you

    th "ตั้งแต่นั้นเป็นต้นมา แมรี่ก็เข้ามาตีสนิทกับเรา"
    en "From then on, Mary started to befriend me."
    th "ตอนแรกก็รำคาญอยู่บ้าง แต่ไปๆมาๆ เราก็ชินกับการที่แมรี่ชวนคุยเรื่องไม่เป็นเรื่อง"
    en "At first, I found it annoying, but gradually I got used to Mary starting conversations about trivial matters."
    th "แมรี่ชอบเข้ามาหาเราและแกล้งให้เราตกใจ ต่อจากนั้นก็จะหาปริศนาแปลกๆมาให้เราไขอยู่เรื่อย"
    en "She liked to come to me, startle me playfully, and then present me with strange riddles to solve."

    voice "audio/voice/final/mary_10_015.mp3"
    mary_th  "ไขให้ได้สิจ้ะ ฮะๆๆ"
    mary_en "Try to solve it, hehe!"
    yume_th  "ฉันอ่านอักษรรูนไม่รู้เรื่อง ฉันจะไขยังไง?"
    yume_en "I can't read runes. How am I supposed to solve this?"
    voice "audio/voice/final/mary_10_016.mp3"
    mary_th  "ใช้ความพยายามจ้ะ เดี๋ยวมันก็ได้เอง"
    mary_en "Just put in some effort, you'll get it."
    yume_th  "ฉันไม่อยากใช้ความพยายามกับของแบบนี้สักนิด เฮ้อ"
    yume_en "I don't want to put effort into something like this. Sigh."
    voice "audio/voice/final/mary_10_017.mp3"
    mary_th  "โอวว คนใจร้าย"
    mary_en "Oh, such a cold heart."
    th "ปริศนาของแมรี่มีมากมายไม่รู้จบ"
    en "Mary's puzzles were endless and varied."
    th "มีทั้งที่ง่ายจนน่าตลก ยากจนชวนปวดหัวและกวนประสาทจนฟังเฉลยแล้วเรารับไม่ได้"
    en "s   ome were so easy they were laughable, others so difficult they gave me headaches, and some so annoying that I couldn't accept the solutions when I heard them."

    scene classroom_morning with dissolve
    th "เวลาผ่านไปหลายเดือน"
    en "Months passed"
    th "พวกเราสองคนสนิทกันถึงขนาดไปไหนมาไหนด้วยกันตลอดเวลา" 
    en "Mary and I grew inseparable, to the point where we were almost always together."
    th "ถึงส่วนมากจะเป็นแมรี่เดินไล่ตามเรามากกว่าก็เถอะนะ"
    en "Although, it was mostly Mary following me around."

    voice "audio/voice/final/mary_10_018.mp3"
    mary_th "วันนี้มีปริศนามาให้ทายจ้ะ"
    mary_en "I've got a new riddle for you today."
    yume_th "ไม่เอาได้ไหม?"
    yume_en "Can we not do this?"
    voice "audio/voice/final/mary_10_019.mp3"
    mary_th "ใจร้าย!"
    yume_en "You're so mean!"
    yume_th "คราวก่อนก็ password is easier than you think มุกขายขำแบบนั้นไม่เอาอีกแล้วนะ"
    yume_en "Last time it was 'password is easier than you think'. I don't want any more of those cheesy jokes."
    voice "audio/voice/final/mary_10_020.mp3"
    mary_th "เธอไม่คิดว่ามันตลกดีเหรอจ้ะ?"
    mary_en "Don't you think it was funny?"
    yume_th "คนทายน่ะตลก แต่คนตอบน่ะปวดหัว"
    yume_en "The guesser, maybe. But the answerer? It's a headache."
    voice "audio/voice/final/mary_10_021.mp3"
    mary_th "ใจความสำคัญอยู่ที่ฉันขำจ้ะ"
    mary_en "The point is, I find it funny."
    yume_th "แล้วฉันล่ะ?"
    yume_en "What about me?"
    voice "audio/voice/final/mary_10_022.mp3"
    mary_th "การถามปริศนาเล่นมุก ต้องมีฝ่ายใดฝ่ายหนึ่งเสียสละอยู่แล้วจ้ะ"
    mary_en "In riddle-telling and joking, one side has to make a sacrifice."
    yume_th "ฉันไม่รู้จะว่าอะไรกับเธอเลย"
    yume_en "I don't even know what to say to you anymore."
    th "วันคืนอันไร้แก่นสารหมดไปกับการคุยเรื่องไร้สาระและทายปัญหาชวนหัว"
    en "Our days and nights were spent in seemingly pointless conversations and puzzling over brain teasers."
    th "ถึงจะไร้แก่นสารแต่มันก็ไม่ได้แย่"
    en "Though they might have seemed trivial, these moments weren't bad at all."
    th "เพราะการใช้เวลาร่วมกันกับแมรี่ทำให้เราดีใจอย่างบอกไม่ถูก"
    en "Spending time with Mary brought me a joy I couldn't quite explain."
    scene nightsky
    stop music
    play music 手紙のさよなら

    th "เราเคยถามแมรี่ว่าเธอมีโอกาสหาเพื่อนคนอื่นตั้งมากมาย ทำไมเธอถึงมาสนิทกับเราคนเดียว"
    en "I once asked Mary why, with so many opportunities to make other friends, she chose to become close to me alone."
    th "ช่วงแรกเธอไม่ยอมตอบคำถามนี้ให้เรา ทุกครั้งที่เราถามเธอ แมรี่จะแสดงสีหน้าลำบากใจ ไม่ก็พยายามเปลี่ยนเรื่องเป็นการทายปริศนาที่เธอชอบแทน"
    en "Initially, she avoided answering this question. Every time I asked, Mary would look uncomfortable or try to change the subject with one of her favorite riddles."
    th "หลังจากอยู่ด้วยกันหลายเดือน เพื่อนสนิทคนแรกของเราก็พูดความจริง"
    en "After several months together, my first true friend finally told me the truth."
    th "พวกเราสองคนมีปูมหลังที่คล้ายกัน"
    en "We shared similar backgrounds."
    th "แมรี่เห็นเราถูกทิ้งเลยเข้าใกล้เรา"
    en "Mary approached me because she saw me being left out"
    th "ทั้งหมดเพราะเธอไม่อยากให้เราอยู่คนเดียว"
    en "She didn't want me to be alone."

    voice "audio/voice/final/mary_10_023.mp3"
    mary_th "ครอบครัวของฉันค่อนข้างมีปัญหาน่ะ"
    mary_en "My family is quite troubled."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_024.mp3"
    mary_th "ปัญหาอาจจะไม่ได้ใหญ่เท่าเธอ แต่มันก็ทำให้ฉันมองหน้าคนในบ้านไม่ติดอยู่ดีจ้ะ"
    mary_en "It might not be as serious as yours, but I still can't stand to face the people in my house."
    th "นั่นเป็นไม่กี่ครั้งที่เราเห็นแมรี่ทำหน้าเศร้า"
    en "That was one of the few times I saw Mary look sad."
    th "เด็กสาวผมทองที่เจิดจ้าราวกับดวงอาทิตย์หุบยิ้มลง ทำให้โลกดูมืดหม่นลงทันใด"
    en "The normally bright and sunny blond-haired girl suddenly seemed to darken the world around her."
    voice "audio/voice/final/mary_10_025.mp3"
    mary_th "พ่อกับแม่ของฉันไม่ได้รักกันจริงๆ พวกเขาแต่งงานกันเพราะเรื่องทางธุรกิจ"
    mary_en "My parents don't really love each other. They married for business reasons."
    yume_th "แนวๆตระกูลร่ำรวยสองตระกูลดองญาติกันเพื่อผลประโยชน์เหรอ?"
    yume_en "Like two wealthy families joining together for mutual benefits?"
    th "แมรี่พยักหน้าด้วยสีหน้าขึงขัง"
    en "Mary nodded, her expression tense."
    th "หาได้ยากจริงๆที่คนร่าเริงอย่างเธอจะแสดงด้านนี้ออกมา"
    en "It was rare to see such a cheerful person show this side of herself."
    voice "audio/voice/final/mary_10_026.mp3"
    mary_th "พ่อและแม่ของฉันทะเลาะกันบ่อยๆ"
    mary_en "My parents argue a lot."
    yume_th "....."    
    yume_en "....."  
    voice "audio/voice/final/mary_10_027.mp3"
    mary_th "ครอบครัวของฉันเห็นฉันเป็นลิ่มที่ตรึงทั้งสองครอบครัวเข้าด้วยกัน คุณค่าของฉันมีแค่นั้นแหละ เพราะแบบนั้น...บางครั้งพวกเขาก็มาทำร้ายฉันเพราะฉันเป็นลูกที่พ่อแม่ไม่ต้องการ..."
    mary_en "In my family, I'm seen as a mere pin holding the two families together. My worth is only that. Because of this... sometimes they hurt me, because I am the child they never wanted..."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_028.mp3"
    mary_th "อย่าทำหน้าเครียดสิ...ถึงตอนเด็กๆจะโดนเล่นงานบ่อยๆ แต่พอโตขึ้นก็ไม่ค่อยโดนแล้วล่ะ...ฮะๆ"
    mary_en "Don't look so worried... I was bullied a lot as a child, but it doesn't happen much anymore... Haha."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_029.mp3"
    mary_th "เรื่องมันไม่น่าฟังเลยนะ ว่าไหม?"
    mary_en "It's a pretty sad story, isn't it?"
    th "แมรี่ส่งยิ้มเศร้าๆให้กับเรา แม้กระทั่งเสียงหัวเราะของเธอยังดูเป็นการฝืนเลย"
    en "Mary gave me a sad smile, even her laughter seemed forced."
    yume_th "พวกผู้ใหญ่นี่เฮงซวยจังเนอะ"
    yume_en "Adults can be so cruel."
    voice "audio/voice/final/mary_10_030.mp3"
    mary_th "ก็ถูกจ้ะ แต่คงไม่ใช่ทุกคนหรอก"
    mary_en "That's true. But not all of them."
    yume_th "เธอนี่มองโลกในแง่ดีจังนะ"
    yume_en "You're really optimistic, aren't you?"
    voice "audio/voice/final/mary_10_031.mp3"
    mary_th "ยูเมะต่างหากที่มองโลกในแง่ร้ายเกินไปจ้ะ"
    mary_en "It's you, Yume, who sees the world too negatively."

    th "แมรี่ส่ายหน้าเบาๆก่อนจะส่งยิ้มให้เราอีกครั้ง"
    en "Mary shook her head lightly and smiled at me again."
    th "ทั้งๆที่มีปัญหาชีวิตเหมือนกัน แต่เธอกลับยิ้มได้อย่างสดใส ตรงข้ามกับเราโดยสิ้นเชิง"
    en "Despite having a troubled life like me, she could still smile so brightly, completely opposite to me."
    th "สำหรับเราแล้ว แมรี่เป็นคนพิเศษยิ่งกว่าใคร"
    en "To me, Mary was more special than anyone else."
    th "การได้ใช้เวลากับเธอทำให้เรารู้สึกว่าโลกนี้ยังมีอะไรดีๆอยู่บ้าง"
    en "Spending time with her made me feel that there was still some good in the world."
    th "เราดีใจจริงๆที่ได้เจอเธอ"
    en "I'm genuinely glad to have met her."
    scene classroom_morning with dissolve
    stop music
    play music 神隠しの真相

    th "วันหนึ่ง ความสัมพันธ์ของพวกเราก็เปลี่ยนแปลงไป"
    en "One day, the nature of our relationship changed."
    yume_th "ถ้าเธอดื่มจากแก้วฉัน มันก็เป็นจูบทางอ้อมพอดีสิ"
    yume_en "If you drink from my glass, it's almost like an indirect kiss, isn't it?"
    voice "audio/voice/final/mary_10_032.mp3"
    mary_th  "แค่นั้นก็อายเหรอ?"
    mary_en "Is that enough to make you shy?"
    yume_th "อายสิ"
    yume_en "Yes, it is."
    voice "audio/voice/final/mary_10_033.mp3"
    mary_th "ฮิๆ"
    mary_en "Hehe."
    yume_th "...!!"
    th "...!!"
    en "Before I could finish speaking, my words were halted."
    th "กลิ่นอันหอมหวลและปอยผมสีทองยาวสลวยของคนตรงหน้าปลิวไสวไล้เลียใบหน้าของเรา"
    en "The sweet fragrance and the long, golden hair of the person in front of me brushed against my face."
    th "สัมผัสนุ่มนวลและอบอุ่นปรากฏขึ้นบนริมฝีปากของเรา ก่อนที่การเชื่อมต่อระหว่างเราสองคนจะถูกคลี่คลายลงเมื่อคนตรงหน้าเลื่อนใบหน้าห่างออกไป"
    en "A soft and warm touch appeared on my lips before the connection between us was gently broken as she pulled her face away."
    th "ใบหน้าของเธอแดงระเรื่อน้อยๆ"
    en "Her face was slightly flushed."
    th "แน่นอนว่าตอนนี้ใบหน้าของเราก็แดงไม่แพ้เธอ"
    en "My face was undoubtedly as red as hers."   
    yume_th "เมื่อกี้นี้มัน..."
    yume_en "What just happened..."
    voice "audio/voice/final/mary_10_034.mp3"
    mary_th "ฉันจะไม่โกหกความรู้สึกของฉันจ้ะ"
    mary_en "I won't lie about my feelings."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_035.mp3"
    mary_th "ฉันน่ะ...ชอบเธอที่สุดเลย..."
    mary_en 'I... like you the most...'

    scene sky_morning
    stop music
    play music 手紙のさよなら

    th "แมรี่สารภาพความรู้สึกกับเราว่าเธอคิดกับเรามากกว่าเพื่อน"
    en "Mary confessed that her feelings for me were more than just friendship."
    th "สำหรับเรา เราไม่แน่ใจว่าความรู้สึกของเราคือความรักหรือเปล่า แต่สิ่งที่เรามั่นใจคือเราอยากอยู่ข้างๆแมรี่ เราไม่ให้เธอจากเราไปไหน"
    en "As for me, I wasn't sure if what I felt was love, but I was certain that I wanted to be by Mary's side. I didn't want her to leave."
    th "การที่มีแมรี่อยู่ข้างๆทำให้เราลืมชีวิตที่เลวร้ายของเรา"
    en "Having Mary near me made me forget about my miserable life."
    th "มันทำให้เรามีความสุข เพราะฉะนั้นเราจึงตอบรับความรู้สึกของแมรี่"
    en "She brought me happiness, so I reciprocated her feelings."
    th "...เราคิดว่าเรื่องราวจะจบลงอย่างมีความสุขเท่านั้น..."
    en "I thought that would be the happy end of our story..."
    th "...แต่ในความจริงแล้ว...มันไม่ได้ง่ายแบบนั้นเลย..."
    en "but reality wasn't that simple..."


    scene black with dissolve
    th "ความรู้สึกเจ็บปวดทรมานค่อยๆเลือนหายไป"
    en "The pain and torment gradually faded away."
    th "ร่างกายของเราขยับไปตามสัญชาตญาณ"
    en "My body moved on instinct."
    th "รู้ตัวอีกทีเราก็เดินผ่านประตูบานหนึ่งและเข้ามาในห้องถัดไปแล้ว"
    en "Before I knew it, I had passed through a door and entered the next room."
    scene white with dissolve
    scene fb3_3 with dissolve
    stop music
    play music 廃墟洋館

    th "ท่ามกลางห้องที่น่าคุ้นเคยคือเด็กสาวผมทองที่กำลังรอเราอยู่"
    en "In a familiar room stood the blond-haired girl, waiting for me."
    yume_th "แมรี่"
    yume_en "Mary..."
    voice "audio/voice/final/mary_10_036.mp3"
    mary_th "ในที่สุด เธอก็มาถึงห้องสุดท้ายสินะ"
    mary_en "Finally, you've reached the last room."
    th "เด็กสาวผมทองส่งยิ้มเศร้าๆให้เรา"
    en "The blond-haired girl gave me a sad smile."
    th "เราเข้าใจแล้ว แท้ที่จริง เธอคนนี้เฝ้าทองเรามาตลอด"
    en "I understood then that she had been watching over me all this time."
    yume_th "เธอคือแมวตัวนั้น"
    yume_en "You are that cat."
    voice "audio/voice/final/mary_10_037.mp3"
    mary_th "เรื่องแค่นั้นไม่น่าเดายากจ้ะ"
    mary_en "It wasn't hard to guess."

    th "คนกลายร่างเป็นแมวได้เป็นเรื่องที่น่าขำ แต่การมีอยู่ของคฤหาสน์ที่เปลี่ยนฉากในห้องได้อย่างอิสระและมีทางเดินที่ไม่มีจุดสิ้นสุดก็ดูเป็นเรื่องเหนือธรรมชาติอยู่แล้ว"
    en "It seemed ridiculous that a person could transform into a cat, but in a mansion where rooms changed scenes at will and corridors never ended, it didn't seem so far-fetched."
    th "การที่แมรี่กลายร่างได้อาจจะเป็นเรื่องที่ไม่ผิดแปลกในสถานที่แบบนี้"
    en "In a place like this, Mary's transformation could be considered normal."
    th "ที่สำคัญคือ..."
    en "But the real question was..."
    yume_th "ที่นี่คือที่ไหนกัน?"
    yume_en "Where are we?"
    voice "audio/voice/final/mary_10_038.mp3"
    mary_th "อย่าถามคำถามที่เธอแสร้งทำเป็นไม่รู้คำตอบสิ ยูเมะ"
    mary_en "Don't ask questions when you pretend not to know the answer, Yume."
    yume_th "หา?"
    yume_en "Huh?"
    th "เราอุทานขึ้นด้วยความไม่เข้าใจ"
    en "I exclaimed in confusion."
    th "แมรี่กำลังพูดอะไร เธอต้องอะไรจากเรากันแน่"
    en "What was Mary talking about? What did she want from me?"
    voice "audio/voice/final/mary_10_039.mp3"
    mary_th "เธอเข้ามาที่นี่โดยที่ไม่มีร่างกายและไม่มีความทรงจำ แต่นั่นน่ะ...มันเกิดจากการรับรู้ที่ผิดพลาดของเธอเอง..."
    mary_en "You came here without a body and without memories."
    yume_th "เธอพูดอะไร...?"
    yume_en "What are you saying...?"
    voice "audio/voice/final/mary_10_040.mp3"
    mary_th "จิตใจของเธอไม่สามารถยอมรับกับความเป็นจริงได้ เธอเลยทำเป็นไม่เห็นทุกสิ่งทุกอย่าง"
    mary_en  "Your mind couldn't accept reality, so you chose to ignore everything."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_041.mp3"
    mary_th "นึกให้ออกสิว่าทำไมฉันถึงอยู่ที่นี่ ทำไมเธอถึงตามฉันมาที่นี่"
    mary_en "Think about why I am here. Why you followed me here."
    yume_th  "...อึก"
    yume_en "...Ugh"
    th "คำพูดของแมรี่ทำให้เรารู้สึกปวดหัว"
    en "Mary's words caused me a headache."
    th "ความรู้สึกที่เหมือนสมองจะถูกฉีกเป็นเสี่ยงๆนี่มันอะไร?"
    en "What was this feeling, as if my brain was being torn apart?"
    th "....."
    en "....."
    th "ทันใดนั้น...ภาพตรงหน้าก็มืดดำลงอีกครั้ง..."
    en "Suddenly... everything in front of me turned dark once again..."
    th "...ความทรงจำมากมายกำลังหลั่งไหลกลับมา..."
    en "...Memories started flooding back..."
    scene rouka_main with dissolve
    stop music
    play music house_of_terror 

    th "เวลาผ่านไป เราคบหากับแมรี่มาสองปี"
    en "We had been dating Mary for two years."
    th "เราพอใจกับความสัมพันธ์ที่เกิดขึ้น เราเลยเลือกจะอยู่ข้างๆแมรี่โดยไม่สนว่าเราเป็นเพศเดียวกันหรือมีปัญหาทางครอบครัวไม่ต่างกัน"
    en "Content with our relationship, I chose to stay by her side, undeterred by our same-sex status or our similar family issues."
    th "เราในตอนนั้นอยู่ในห้วงแห่งความสุข จนสุดท้ายก็หมางเมินความจริง"
    en "In that time, I was lost in happiness, ignoring the reality of our situation."
    th "....."
    en "....."
    scene sky_cloudy with dissolve
    th "วันนั้นเป็นคืนที่ฝนตกหนัก"
    en "That day, it was a heavy rainy night."
    th "เราไปหาแมรี่ที่คฤหาสน์ของเธอ แต่แมรี่มีท่าทางลำบากใจ"
    en "I went to see Mary at her mansion, but she seemed uneasy."
    th "ดูเหมือนว่าแมรี่จะไม่อยากให้เราเจอกับครอบครัวของเธอ"
    en "It appeared she didn’t want me to meet her family."

    scene main_castle with dissolve
    father_th "แกพาใครมาเนี่ย เจ้าลูกไม่ได้เรื่อง?"
    father_en "Who did you bring here? Useless daughter?"
    th "ชายวัยกลางคนที่น่าจะเป็นพ่อของแมรี่เดินเข้ามาแทรกระหว่างเรากับแมรี่"
    en "Mary's father, a middle-aged man who I presumed to be her father, interrupted us."
    th "เขาถามแมรี่ก่อนจะมองใบหน้าเราถมึงทึง สายตาแหลมคมของเขาทำให้เรารับรู้ในทันที"
    en "He questioned Mary before giving me a sharp, piercing look."
    th "คนๆนี้เป็นตัวอันตราย"
    en "I immediately sensed danger."
    voice "audio/voice/final/mary_10_042.mp3"
    mary_th "พ่อ...พ่อคะ..."
    mary_en "Father... Dad..."
    father_th "ถามก็ตอบสิ อย่ามาอ้ำอึ้ง"
    father_en  "Answer me! Don't stand there stammering!"
    yume_th "ฉันเป็นแฟนของแมรี่ค่ะ"
    yume_en "I am Mary's girlfriend."
    th "เราเห็นแมรี่หวาดกลัวพ่อ เราเลยรีบออกตัวปกป้องเธอ"
    en "I saw fear in Mary's eyes towards her father, so I stepped in to protect her."
    th "ดวงตาของพ่อแมรี่เบิกโพลง"
    en "Her father's eyes widened in shock."
    th "เราหาได้รู้ไม่เลยว่าเราได้พูดสิ่งที่อันตรายที่สุดออกไป"
    en "I had unwittingly said something terribly dangerous."
    th "ตึงงง!!"
    en "Suddenly"
    th "เราไม่อยากเชื่อสายตาตัวเอง"
    en "I couldn't believe my eyes"
    th "ภาพที่เราเห็นคือกำปั้นชายวัยกลางคนกระแทกเข้าที่ใบหน้าของผู้หญิงที่เรารัก"
    en "the man's fist struck the face of the woman I loved."
    yume_th "แมรี่!"
    yume_en "Mary!"
    th "เรารีบพยุงร่างของแมรี่ที่โซซัดโซเซ"
    en "I rushed to support Mary, who was staggering."
    th "เรือนผมสีทองยาวสลวยปรากฏเลือดสีแดงฉานแต่งแต้มเป็นแนวยาว"
    en "Her long, blond hair was stained with a vivid trail of blood."
    yume_th "นี่คุณทำบ้าอะไร!?"
    yume_en "What are you doing!?"
    th "เราตะคอกใส่พ่อแมรี่ด้วยความเหลืออด แต่เขากลับมองเราด้วยสายตาอาฆาตแค้น"
    en "I yelled at Mary's father in fury, but he looked back with vengeful hatred."
    th "ความเกลียดชังอันบริสุทธิ์ทะลักออกมาจากแววตาของพ่อแมรี่"
    en "Pure loathing poured from his eyes."
    father_th "แกก็เป็นเหมือนแม่แกอีกคนเหรอ! นังลูกโง่!"
    father_en "Another fool like your mother! Useless daughter!"
    voice "audio/voice/final/mary_10_043.mp3"
    mary_th "...อึก"
    mary_en "...Ugh"
    yume_th "หา?"
    yume_en "What?"
    th "เขาตะโกนราวกับคนเสียสติ สายตาของเขาไม่ได้มองเรากับแมรี่ตรงๆด้วยซ้ำ"
    en "He screamed like a madman, his eyes not focusing on us."
    th "ชายวัยกลางคนที่ส่งเสียงร้องราวกับสัตว์เดรัจฉานไม่มีผิด"
    en "He was like a beast, unrecognizable as human."
    father_th "ทำเป็นรักแต่ผู้หญิงเหมือนแม่แก สุดท้ายแกจะหนีตามนังนั่นเหมือนแม่แกอีกคนไหม?"
    father_en "Pretending to love a woman like your mother. Will you run away with her like she did?"
    voice "audio/voice/final/mary_10_044.mp3"
    mary_th "พ่อคะ หนูก็แค่..."
    mary_en "Dad, I just..."
    father_th "ใครๆก็รู้ว่าครอบครัวเราแต่งงานเพื่อธุรกิจ แต่ใครมันจะไปทนอยู่กับพวกวิปริตทางเพศได้วะ"
    father_en "Everyone knows our family married for business. Who could stand being with perverts!"
    
    mary_th "....."
    mary_th "....."
    father_th "แกรู้ไหมว่ามันยุ่งยากแค่ไหนที่ฉันต้องมานั่งลบข่าวฉาวเรื่องแม่แกหนีตามกับผู้หญิงที่เป็นคนรักเก่า แม่แกทำให้ชื่อเสียงของฉันป่นปี้ไปหมด!"
    father_en  "Do you know how hard it was for me to cover up the scandal of your mother running away with her lover? She ruined my reputation!"
    th "เสียงตะคอกของชายวัยกลางคนแทรกผ่านเข้ามาในโสตประสาทของเรา"
    en "His yelling pierced my ears."
    th "คำพูดเหยียดหยามครอบครัวแท้ๆทำให้ความโกรธแค้นเริ่มกลืนกินเราเข้าไป สำหรับคนที่เกลียดครอบครัวตัวเองเหมือนกัน เราไม่สามารถทนฟังชายคนนี้ด่าทอลูกสาวตัวเองได้"
    en "His disparaging words about his own family ignited an unbearable rage in me."
    th "เรากำหมัดแน่นพร้อมจะผุดลุกขึ้นต่อหน้าพ่อแมรี่"
    en "I clenched my fists, ready to confront Mary's father"
    th "อย่างไรก็ตาม แมรี่กลับหยุดเราไว้"
    en "But Mary stopped me."
    th "เธอมองออกว่าถ้าเราประจันหน้ากับพ่อเธอ จะไม่มีผลลัพธ์ดีๆตามมาทั้งนั้น"
    en "She knew confronting her father wouldn't end well."

    voice "audio/voice/final/mary_10_046.mp3"
    mary_th "ใจเย็นๆก่อน ยูเมะ"
    mary_en "Calm down, Yume."
    yume_th "แต่ว่า...!"
    yume_en "But...!"
    voice "audio/voice/final/mary_10_047.mp3"
    mary_th "อย่าลงมือ"
    mary_en "Don't do it."
    yume_th "...!!"
    yume_en "...!!"
    voice "audio/voice/final/mary_10_048.mp3"
    mary_th "เธอเคยบอกฉันใช่ไหมว่าเธอจะไม่เป็นอย่างแม่เธอ"
    mary_en "You said you wouldn't be like your mother."
    th "คำพูดของแมรี่เสียดแทงเข้าไปในจิตใจของเรา"
    en "Her words cut deep."
    th "แม้มันจะเป็นคำพูดเมื่อนานมาแล้ว แต่เธอยังคงจำมันได้"
    en "Even though it was a long time ago, she remembered them."
    yume_th "...ฉัน..."
    yume_en "I..."
    th "คำพูดของเราขาดห้วงเพราะความคิดอันวุ่นวาย"
    en "My words were lost in turmoil."
    scene black with dissolve
    th "วูบบ!!"
    en "Flashed!!"
    th "ชั่วพริบตานั้น พ่อของแมรี่ที่บันดาลโทสะก็พุ่งเข้ามาพร้อมกับเหวี่ยงหวัด"
    en "In an instant, Mary's father, blinded by rage, lunged at us, his target being his own daughter, following in her mother's footsteps."
    th "เป้าหมายของเขาไม่มีใครอื่นนอกจากลูกสาวแท้ๆ ผู้เดินตามรอยภรรยาที่เขาเกลียดชัง"
    yume_th "...!!"
    yume_en "...!!"
    th "ช่วงเวลานั้น เรามีเจตนาเพียงแค่จะปกป้องแมรี่"
    en "In that moment, my only intention was to protect Mary."

    #blood scren
    scene blood with dissolve
    voice "audio/voice/final/mary_10_049.mp3"
    mary_th "ไม่นะ!! ยูเมะ!!"
    mary_en "No!! Yume!!"
    th "เสียงกรีดร้องของแมรี่ดังขึ้น"
    en "Her scream echoed. The next thing I knew, I had ended a life."
    scene black with dissolve
    th "รู้สึกตัวอีกที เราก็จบชีวิตคนคนหนึ่งไปแล้ว"

    scene fb3_4 with dissolve
    stop music
    play music 廃墟洋館

    voice "audio/voice/final/mary_10_050.mp3"
    mary_th "จำได้หรือยังล่ะ?"
    mary_en "Do you remember now?"
    yume_th "...นี่มัน..."
    yume_en "...This is..."
    voice "audio/voice/final/mary_10_051.mp3"
    mary_th "เธอต้องการจะปกป้องฉัน แต่อุบัติเหตุได้เกิดขึ้น"
    mary_en "You wanted to protect me, but an accident happened."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_052.mp3"
    mary_th "เธอผลักพ่อของฉันจนหัวเขากระแทกกลอนประตูโลหะ สาเหตุการตายของพ่อคือเลือดออกในสมอง"
    mary_en "You pushed my father, and his head hit the metal door lock. He died of a brain hemorrhage."
    yume_th "...อึก"
    yume_en "...Ugh"
    th "ความรู้สึกผิดในอดีตค่อยๆหลั่งไหลกลับมา"
    en "Guilt from the past slowly crept back into my consciousness."
    th "ท้ายที่สุดเราก็กลายเป็นฆาตกรเหมือนแม่ของเรา"
    en "In the end, I had become a murderer like my mother."
    th "นี่มันตลกร้ายชัดๆ"
    en "A cruel irony."
    yume_th "เธอคง...แค้นฉันสินะ..."
    yume_en "You must... hate me..."
    th "แมรี่ทำหน้าเศร้าขณะที่เธอส่ายหน้าปฏิเสธ"
    en "Mary looked sad as she shook her head."
    voice "audio/voice/final/mary_10_053.mp3"
    mary_th "เรื่องที่เกิดขึ้นไม่มีใครตั้งใจหรอกจ้ะ"
    mary_en "What happened wasn't intentional."
    yume_th "แมรี่..."
    yume_en "Mary..."
    voice "audio/voice/final/mary_10_054.mp3"
    mary_th "ฉันไม่โกรธแค้นเธอหรอก เพราะเธอแค่อยากปกป้องฉันใช่ไหมล่ะ"
    mary_en "I don't blame you. You just wanted to protect me."
    th "รอยยิ้มของแมรี่ทำให้เรารู้สึกผิดบาป"
    en "Mary's smile made me feel even more guilty."
    th "จริงอยู่ที่พ่อของแมรี่เป็นคนไม่ดี แต่การฆ่าคนก็ยังเป็นการฆ่าคนอยู่ดี"
    en "Although Mary's father was a terrible person, taking a life is still taking a life."
    th "ตั้งใจหรือไม่ตั้งใจ ฆ่าคนดีหรือคนไม่ดี...ฆาตกรก็ยังเป็นฆาตกร..."
    en "Intentional or not, a murderer is still a murderer."
    yume_th  "แล้วหลังจากนั้น...?"
    yume_en "And after that...?"
    voice "audio/voice/final/mary_10_055.mp3"
    mary_th "เธอถูกจับเข้าเรือนจำข้อหาฆ่าคนตาย"
    mary_en "You were arrested for manslaughter."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_056.mp3"
    mary_th "เธอยอมรับโทษแต่โดยดี พวกเราสองคนสัญญากันว่าหลังจากเธอพ้นโทษแล้ว พวกเราจะกลับมาอยู่ด้วยกันอีกครั้งหนึ่ง"
    mary_en "You accepted your sentence willingly. We promised that once you were out, we would be together again."
    th "แมรี่ตอบเราด้วยรอยยิ้มเศร้าๆ"
    en "Mary gave me a sad smile."
    th "ตั้งแต่วันที่เราจากกัน เวลาผ่านมานานแค่ไหนแล้ว? ที่สำคัญกว่านั้นคือทำไมเราสองคนถึงมาอยู่ในคฤหาสน์ที่ผิดธรรมชาติแบบนี้ได้"
    en "How long had it been since we were separated? More importantly, how did we end up in this unnatural mansion?"
    th "ทุกคำถามในใจล้วนไม่มีคำตอบทั้งสิ้น"
    en "Every question in my heart remained unanswered."
    yume_th  "แล้ว...เรื่องราวต่อจากนั้นล่ะ...?"
    yume_en "And... what happened next...?"
    #voice "audio/voice/final/mary_10_057.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "แมรี่ ตอบฉันที"
    yume_en "Mary, tell me."

    th "แมรี่ส่ายหน้าอีกครั้ง"
    en "Mary shook her head again."
    voice "audio/voice/final/mary_10_058.mp3"
    mary_th  "ฉันตอบคำถามคนที่ไม่รู้ความจริงได้ แต่ฉันไม่สามารถตอบคำถามคนที่ไม่ยอมรับความจริงได้จ้ะ"
    mary_en "I can answer the questions of someone unaware of the truth, but I cannot answer someone who refuses to accept it."
    yume_th  "...หา?"
    mary_en "...What?"
    voice "audio/voice/final/mary_10_059.mp3"
    mary_th "ไม่ว่าฉันจะเฉลยตรงๆสักกี่ครั้ง คนไม่ยอมรับความจริงก็จะทำเป็นลืมทุกอย่าง สุดท้ายฉันเลยต้องสร้างวิธีการพิเศษขึ้นมาเพื่อให้เธอค่อยๆกลับมาเป็นตัวเองอีกครั้ง"
    mary_en "No matter how many times I explain it, someone who denies the truth will pretend to forget everything. So, I had to create a special way to help you slowly return to yourself."
    th "วิธีการ?"
    en "Special way?"
    th "อย่าบอกนะว่า โจทย์กับประตูพวกนั้น?"
    en "You mean those puzzles and doors?"
    voice "audio/voice/final/mary_10_060.mp3"
    mary_th "สำหรับเธอ การตอบปริศนาผ่านประตูอาจจะเป็นครั้งแรก แต่สำหรับฉัน ฉันได้นำทางเธอมาแล้วหลายต่อหลายครั้ง"
    mary_en "For you, solving puzzles and passing through doors might seem new, but for me, I've guided you through this many times."
    th "คำพูดของแมรี่ทำให้เราเบิกตาโพลง"
    en "Mary's words left me stunned."
    voice "audio/voice/final/mary_10_061.mp3"
    mary_th "ทุกครั้งที่เธอใกล้ถึงปลายทาง เธอจะวิ่งหนีจากความจริง และพวกเราก็จะเริ่มใหม่กันอีกครั้ง..."
    mary_en "Every time you near the end, you run from the truth, and we start over..."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_062.mp3"
    mary_th "ในมุมมองของเธอ เธออาจจะผ่านเส้นทางนั้นมาครั้งเดียว แต่ในความจริงแล้ว พวกเราทั้งสองได้เดินผ่านประตูพวกนั้นมาไม่รู้กี่สิบกี่ร้อยครั้ง"
    mary_en "In your perception, you might have walked this path once, but in reality, we've passed through those doors countless times."


    yume_th "..ไม่จริง"
    yume_en "...It can't be true."
    voice "audio/voice/final/mary_10_063.mp3"
    mary_th "มันคือความจริง ยูเมะ"
    mary_en "It is the truth, Yume."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_064.mp3"
    mary_th "ฉันดีใจนะที่เธอสามารถไขปริศนาทั้งหมดและมาถึงห้องสุดท้ายนี้ได้"
    mary_en "I'm glad you could solve all the puzzles and reach this final room."


    stop music
    play music crystal_battle
    
    th "แมรี่จับจ้องเราด้วยสายตาขึงขัง "
    en "Mary gazed at me with an intense stare."
    th "ความแข็งกร้าวบนใบหน้าที่แสนอ่อนโยนทำให้เรารู้สึกจากใจ"
    en "The firmness on her usually gentle face struck me deeply."
    th "ผู้หญิงที่เรารักกำลังเดิมพันทุกอย่าง"
    en "The woman I loved was risking everything."
    th "...เพื่อช่วยเหลือเรา..."
    en "...For help me..."
    voice "audio/voice/final/mary_10_065.mp3"
    mary_th "เศษเสี้ยวของความจริงชิ้นสุดท้ายเป็นสิ่งที่ต่อให้ฉันพูดให้เธอฟัง เธอก็จะวิ่งหนีจากมัน...ฉะนั้นเธอจึงมีหน้าที่รับรู้และยอมรับมันด้วยตัวของเธอเอง..."
    mary_en "The last fragment of truth is something you'll run from, even if I tell you. So, you need to recognize and accept it yourself..."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/final/mary_10_066.mp3"
    mary_th "จงตอบปริศนาสุดท้ายและรับรู้ความทรงจำที่แท้จริงด้วยพลังของตัวเองซะ ยูเมะ"
    mary_en "Solve the final puzzle and come to terms with the real memories using your own strength, Yume."
    yume_th "...แมรี่..."
    yume_en "...Mary..."
    th "เราพึมพำชื่อของเด็กสาวผมทองตรงหน้า"
    en "I murmured her name, the golden-haired girl standing before me."
    th "นี่คือการเผชิญหน้าระหว่างพวกเราสองคนที่ไม่อาจหลีกเลี่ยง"
    en "This was an unavoidable confrontation between us, a moment where hidden truths would finally surface, demanding acknowledgment and acceptance."

    show puzzle10 with dissolve
    jump answer_roome10

    return

label answer_roome10:

    menu:
        "answer":
            $ input_value = renpy.input("Answer?")
            if prepare(input_value) == "diealongside":
                hide puzzle10
                jump common_end
            
            if prepare(input_value) == "liveabeautifullife":
                hide puzzle10
                jump true_end
            
            th "ยังไม่ใช่คำตอบที่ถูกนะ"
            en "Wrong."
            jump answer_roome10
        "ใบ้หน่อยสิ":
            "ขอยันข้อสุดท้ายเลยหรอ ไปทำเองไป้"
            hide puzzle10
            jump answer_roome10

