label true_end:
    scene black with dissolve
    stop music
    play music 憂鬱

    th "ความทรงจำในอดีตหวนกลับมาอีกครั้ง"
    en "Memories from the past return once again."
    
    th "...เราจำได้แล้ว...ว่าทำไมพวกเราทั้งสองจึงมาอยู่ที่คฤหาสน์แห่งนี้..."
    en "...We remember now... why the two of us came to this mansion..."

    th "ที่นี่ไม่ใช่โลกความเป็นจริง มันคือโลกหลังความตาย"
    en "This place is not the real world; it is the world after death."
    
    th "....."
    en "....."

    scene black with dissolve

    th "หลังจากเราฆ่าคน แม้เราไม่มีเจตนา แต่เราไม่สามารถหลบหนีการลงโทษได้"
    en "After we killed someone, even though it was unintentional, we couldn't escape punishment."

    th "เราถูกตัดสินจำคุกข้อหาฆ่าพ่อของแมรี่"
    en "We were convicted and imprisoned for the murder of Mary's father."
    
    th "ก่อนที่เราสองคนจะจากกัน พวกเราสองคนได้ให้สัญญากัน"
    en "Before the two of us parted, we made a promise to each other."

    th "...เมื่อเราออกจากเรือนจำและเป็นอิสระ พวกเราสองคนจะกลับมาอยู่ด้วยกันอีกครั้งหนึ่ง"
    en "...When we are released from prison and free, we will come back and be together once again."
    
    th "....."
    en "....."

    scene sky_cloudy with dissolve
    th "เวลาผ่านไปหลายปี เราพ้นโทษและออกมาจากเรือนจำ"
    en "Years passed, we served our time and were released from prison."
    
    th "แต่เมื่อเรากลับมาหาแมรี่ ทุกอย่างก็สายไปแล้ว"
    en "But when we returned to find Mary, everything was too late."
    
    th "....."
    en "....."

    scene hospital with dissolve
    th "เราพบร่างไร้สติของแมรี่บนเตียงในโรงพยาบาล"
    en "We found Mary's unconscious body on a hospital bed."

    th "ไม่ว่าเราจะเรียกเธอสักกี่ครั้ง แมรี่ก็ไม่ลืมตาตื่นขึ้น"
    en "No matter how many times we called her, Mary would not open her eyes."

    yume_th "ว่าไงนะคะ?"
    yume_en "What did you say?"

    th "เราไม่อยากเชื่อหูของเราเมื่อได้ยินความจริงจากแพทย์ที่ดูแลแมรี่"
    en "We couldn't believe our ears when we heard the truth from the doctor taking care of Mary."

    th "แมรี่ร่างกายอ่อนแอตั้งแต่เด็กๆแล้ว แต่เธอปิดความลับนี้ไว้และแสร้งทำเป็นแข็งแรงดีต่อหน้าเรา"
    en "Mary's body had been weak since childhood, but she hid this secret and pretended to be strong in front of us."

    th "อวัยวะภายในของเธอล้มเหลวมากขึ้นตามเวลาที่ผ่านไป"
    en "Her internal organs failed more as time passed."

    th "...จนสุดท้ายแมรี่ก็กลายเป็นเจ้าหญิงนิทรา..."
    en "...Until finally, Mary became like a sleeping princess..."

    th "เธอจะมีชีวิตได้อีกไม่กี่วันเท่านั้น"
    en "She only had a few days left to live."

    th "....."
    en "....."

    scene black with dissolve

    th "ความสิ้นหวังทำให้เราหัวเราะและร้องไห้ออกมาพร้อมๆกัน"
    en "The gloom in our heart made us distracted and unfocused."
    
    th "...เอาอีกแล้ว..."
    en "...Here we go again..."

    th "ทั้งเรื่องที่ถูกคนรอบข้างรังแกและตีตัวออกห่างเพราะแม่เป็นฆาตกร"
    en "Being bullied and ostracized by those around us because our mother was a murderer."
    
    th "ทั้งพ่อที่นิสัยเลวร้ายลงหลังจากบ้านเราแตกสาแหรกขาด"
    en "And our father, whose personality worsened after our home was broken."

    
    th "ทั้งเรื่องที่เราฆ่าพ่อของแมรี่โดยไม่ได้ตั้งใจจนถูกจับเข้าเรือนจำ"
    en "And the incident where we accidentally killed Mary's father and got imprisoned."
    
    th "ทุกสิ่งไม่เป็นตามที่เราต้องการ...แต่เราก็ยังอดทนได้..."
    en "Nothing went as we wanted... but we still endured..."
    
    th "....."
    en "....."
    
    th "แต่ว่า...แมรี่..."
    en "But... Mary..."
    
    th "ผู้หญิงที่เรารักที่สุด...ความสุขในชีวิตเราที่ยังหลงเหลืออยู่..."
    en "The woman we loved the most... the remaining happiness in our life..."

    
    th "...พังทลาย..."
    en "...Crumbled..."
    

    th "...ชีวิตของเธอกำลังพังทลายลง..."
    en "...Her life is falling apart..."
    
    th "...ต่อหน้าเรา..."
    en "...Before our eyes..."
    
    th "...โดยที่เรา..."
    en "...While we..."
    th "...เรา..."
    en "...We..."
    
    th "....."
    en "....."
    
    th "...เราไม่สามารถทำอะไรได้แม้แต่อย่างเดียว..."
    en "...Can't do even a single thing..."
    
    th "....."
    en "....."
    th "ยูเมะ" 
    en "Yume"
    
    th "เธอจะมีตัวตนอยู่บนโลกนี้ทำไมกัน?"
    en "Why do you exist in this world?"
    
    th "ในเมื่อเธอไม่สามารถรักษาสิ่งสำคัญของตัวเองเอาไว้ได้"
    en "When you can't even preserve the most important thing to yourself."
    
    th "...แม้แต่อย่างเดียว..."
    en "...Not even one thing..."

    ################################
    scene road with dissolve

    th "ความเจ็บปวดแสนสาหัสก่อตัวขึ้นในอกทั้งๆที่ไม่มีบาดแผล"
    en "The excruciating pain formed in my chest, though there were no visible wounds."
    th "หัวใจของเราเจ็บปวดเหมือนถูกมีดนับสิบรุมฉีกกระชาก"
    en "My heart ached as if torn apart by dozens of blades."
    th "ทั้งที่ยังมีลมหายใจแต่เรารู้สึกเหมือนวิญญาณแหลกสลาย"
    en "Despite breathing, my spirit felt shattered..."
    th "...ภาพตรงหน้ามืดมัว..."
    en "The world before me blurred into darkness. "
    th "ความหวังคืออะไรกัน?"
    en "What was hope?"
    th "...โลกนี้...มันคงไม่มีความหวังสินะ..."
    en "In this world, hope no longer existed..."
    th "....."
    en "....."
    th "รู้ตัวอีกที เราก็กำลังย่างเท้าลงบนถนน"
    en "I found myself stepping onto the road."
    th "สัญญาณไฟยังเป็นสีเขียว รถยังคงวิ่งบนถนนเต็มไปหมด"
    en "The traffic light was still green, cars moving incessantly. "
    th "....."
    en "....."
    th "...นั่นสินะ..."
    en "That's right..."
    th "ถ้าหากต้องเหลืออยู่ตัวคนเดียวแล้วล่ะก็...ขอหายไปซะยังจะดีกว่า..."
    en "If I had to be alone, disappearing might be better..."
    th "...ก็เราน่ะ...สัญญากับเธอไว้แล้วนี่นา..."
    en " After all, I had made a promise to her..."
    th "พวกเราสองคนจะกลับมาพบกันอีกครั้งหนึ่ง"
    en "We were supposed to meet again."

    yume_th "ฉันจะตามเธอไปแล้วนะ แมรี่"
    yume_en "I'm coming to you, Mary."
    th "คำพูดสั่งลาของเราที่ไม่มีใครนอกจากเราได้ยิน"
    en "My farewell, unheard by anyone else."
    th "เราเดินลงบนถนน ไม่ช้าหลังจากนั้น เสียงบีบแตรของรถก็ดังขึ้น"
    en "I walked onto the road, and soon after, the blaring horn of a car sounded."
    th "รถคันหนึ่งประชิดร่างของเราพร้อมกับที่แรงกระแทกมหาศาลถูกส่งผ่านเข้ามาในร่างกาย"
    en "A vehicle approached me closely, and a massive impact jolted through my body."

    
    scene black with Dissolve(0.2)

    th "ภาพตรงหน้าเรามืดลงในพริบตาเดียว"
    en "The world went dark in an instant."
    th "....."
    en "....."
    th "สิ่งที่ไม่มีตัวตนอยู่ย่อมไม่มีทางสัมผัสถึงความเจ็บปวดและความโศกเศร้า"
    en "he non-existent cannot feel pain or sorrow."
    th "เท่านี้ ยูเมะจะได้หายไปสักที"
    en "With this, Yume would finally disappear..."
  
    stop music
    play music reflect

    scene fb3_3 with Dissolve(1)

    th "เราล้มลงทั้งยืนต่อหน้าแมรี่"
    en "I fell to our knees in front of Mary."
    yume_th "อั่ก...อ๊า-------!!!!!"
    yume_en "Ahh... Ahhhh-----!!!!"
    th "ความเจ็บปวดทรมานแทรกผ่านเข้ามาในศีรษะของเราอย่างแสนสาหัส"
    en "The excruciating pain pierced through our head."
    th "ความจริงที่หวนคืนกลับมาทำให้เรารู้สึกทุกข์ทรมานเหลือเกิน"
    en "The truth that resurfaced brought unbearable agony."
    voice "audio/voice/true_end/mary_12_000.mp3"
    mary_th "เธอได้อ่านจดหมายที่ฉันส่งให้แล้วสินะ"
    mary_en "You've read the letter I sent you, haven't you?"
    yume_th "จดหมาย?"
    yume_en "The letter?"
    th "แมรี่หมายถึงจดหมายที่เราเจอในห้องแรกๆ"
    en "Mary referred to the letter we found in the first room."
    th "เราอ่านข้อความในจดหมายนั้นและโยงเข้ากับเฉลยในปริศนาสุดท้าย"
    en "We read the letter and connected it to the solution of the final puzzle."
    th "คำตอบที่แท้จริงคือ จงมีชีวิตอยู่อย่างมีความสุข"
    en "The real answer was 'to live on'."
    th "....."
    en "....."
    voice "audio/voice/true_end/mary_12_001.mp3"
    mary_th "ยูเมะ อย่าโกหกตัวเองอีกเลย"
    mary_en "Yume, stop lying to yourself."
    yume_th "แต่...แต่ว่า!?"
    yume_en "But... But what!?"
    voice "audio/voice/true_end/mary_12_002.mp3"
    mary_th "เธอน่ะไม่ได้ลืมตัวตนของตัวเองหรอก เธอแค่ทำเป็นมองไม่เห็น ทำเป็นลืมทุกอย่างเท่านั้น"
    mary_en "You haven't forgotten who you are. You're just pretending not to see, pretending to forget everything."
    yume_th "...!!"
    yume_th "...!!"
    voice "audio/voice/true_end/mary_12_003.mp3"
    mary_th "จริงอยู่ว่าที่นี่คือขอบเขตระหว่างคนเป็นกับคนตาย แต่มันไม่ได้ทำให้รูปลักษณ์ของเธอกลับสู่ความว่างเปล่าหรอก"
    mary_en "It's true that this place is the boundary between the living and the dead, but it doesn't erase your existence into nothingness."
    yume_th "หมายความว่า..."
    yume_en "That means.."
    voice "audio/voice/true_end/mary_12_004.mp3"
    mary_th "เธอคือคนที่ปฏิเสธตัวตนที่เจ็บปวดของตัวเองและฉันคือคนที่พยายามพาเธอกลับมา"
    mary_en "You are the one who denies your painful identity, and I am the one trying to bring you back."
    yume_th "...อึก"
    yume_en "...Uh"
    th "เด็กสาวผมทองจับจ้องเราด้วยดวงตาขึงขัง"
    en "The blonde girl stared at us with intense eyes."
    th "แมรี่ที่เคยเต็มไปด้วยรอยยิ้มกลับแข็งกร้าวขึ้นราวกับเป็นคนละคน"
    en "Mary, once full of smiles, became stern as if she were someone else."
    th "ทั้งหมดก็เพื่อสิ่งที่เธอยืนหยัด"
    en "All for what she stood for."
    th "...เพื่อเอาเรากลับคืนมา..."
    en "...To bring us back..."


    yume_th "ฮะๆๆ ฮ่าๆๆๆๆๆ"
    yume_en "Ha ha ha hahaha!"
    #voice "audio/voice/true_end/mary_12_005.mp3"
    mary_th "......."
    mary_en "......."
    th "เราหัวเราะออกมา"
    en "We laughed."
    th "มันไม่ใช่เสียงหัวเราะแห่งความยินดี แต่เป็นเสียงหัวเราะที่มีไว้เพื่อประชดประชันตัวเอง"
    en "It wasn't a laugh of joy, but one of self-mockery."
    th "เสียงหัวเราะของเราทำให้แมรี่หน้าหมองลงอย่างเห็นได้ชัด"
    en "Our laughter visibly darkened Mary's expression."
    yume_th "ต่อให้กลับมาจำทุกอย่างได้แล้วมันจะยังไงล่ะ แมรี่"
    yume_en "Even if I remember everything, what then, Mary?"
    #voice "audio/voice/true_end/mary_12_006.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "โลกข้างนอกนั่น มันไม่มีความสุขรออยู่"
    yume_en "The outside world, it doesn't have happiness waiting."
    voice "audio/voice/true_end/mary_12_007.mp3"
    mary_th "...ยูเมะ..."
    mary_en "...Yume..."
    yume_th "เพราะฉันเป็นฉันใช่ไหม? ฉันเลยต้องเจอกับโชคร้ายทั้งหมดนั่น...มันไม่ยุติธรรมเลย..."
    yume_en "Because I am me, right? That's why I have to face all this misfortune... It's not fair..."
    #voice "audio/voice/true_end/mary_12_008.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "ถ้าหากฉันไม่สามารถมีความสุขเมื่อมีชีวิตได้ ฉันก็ไม่ขอมีชีวิตอยู่"
    yume_en "If I can't be happy while alive, then I don't want to live."
    voice "audio/voice/true_end/mary_12_009.mp3"
    mary_th "...นั่นมัน..."
    mary_en "...That's..."
    yume_th "เพื่อรักษาสัญญาที่มีต่อเธอ ต่อให้ต้องเสียอะไรไป ฉันก็จะทำ"
    yume_en "To keep my promise to you, I'll do whatever it takes, even if it means losing something."


    th "...ใช่แล้ว..."
    en "...Yes..."
    th "เราไม่ได้เดินลงบนถนนโดยไม่เข้าใจว่าตัวเองกำลังทำอะไรหรอก"
    en "I didn't walk down that road unaware of what I was doing."
    th "เราเดินลงไปโดยรู้ดีว่าเราต้องตาย"
    en "I walked down knowing I had to die."
    th "...ทั้งหมดเพียงเพื่อรักษาสิ่งสุดท้ายที่เรายังเหลืออยู่...สัญญาที่มีต่อคนที่เรารักที่สุด..."
    en "...All just to keep the last thing I have left... my promise to the person I love most..."
    th "พวกเราสองคนจะกลับมาพบกันอีกครั้งหนึ่ง"
    en "We will meet again one day."
    th "...แม้แต่ความตายก็ไม่อาจพรากจากกัน..."
    en "...Not even death can separate us..."
    yume_th "ฉันไม่สนใจหรอกว่าจะมีคนบอกว่าฉันเป็นคนอ่อนแอหรือเป็นคนบ้า"
    yume_en "I don't care if people say I'm weak or crazy."
    voice "audio/voice/true_end/mary_12_010.mp3"
    mary_th "ยูเมะ"
    mary_en "Yume."
    yume_th "ฉันน่ะ...ก็แค่อยากอยู่กับเธอ..."
    yume_en "I... just want to be with you..."
    #voice "audio/voice/true_end/mary_12_011.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "ได้โปรด อย่าทิ้งฉันไป...แมรี่..."
    yume_en "Please, don't leave me... Mary..."
    th "น้ำตาสองสายหลั่งรินออกมา"
    en "Tears streamed down."
    th "กระแสแห่งความรู้สึกอาบท่วมใบหน้าของเราเต็มไปหมด"
    en "A flood of emotions drenched our face."

    stop music
    play music 泣カナイデ

    th "สัมผัสอบอุ่นโอบรอบร่างที่ทรุดลงกับพื้นของเรา"
    en "A warm embrace enveloped our collapsed form on the ground."
    yume_th "แมรี่"
    yume_en "Mary"
    th "เราพูดชื่อของเจ้าของอ้อมกอดที่โอบอุ้มร่างเรา"
    en "We uttered the name of the one whose arms cradled us."
    th "เด็กสาวผมทองหลั่งน้ำตาให้เราพร้อมกับส่งยิ้มที่แสนเศร้าให้"
    en "The blonde girl shed tears for us, offering a sorrowful smile."
    voice "audio/voice/true_end/mary_12_012.mp3"
    mary_th "ฉันน่ะ...คงเป็นคนเห็นแก่ตัวมากสินะ..."
    mary_en "I must be very selfish..."
    yume_th "หา?"
    yume_en "What?"
    voice "audio/voice/true_end/mary_12_013.mp3"
    mary_th "ทั้งเข้าใกล้เธอและพยายามตีสนิทกับเธอเพราะคิดว่าเธอมีอะไรคล้ายๆกับฉัน ทั้งจงใจทายปริศนาไร้สาระทั้งๆที่รู้ว่าเธอไม่ชอบตอบคำถามฉัน"
    mary_en "Approaching you, trying to get close because I thought you were like me, intentionally solving those absurd puzzles even though I knew you disliked answering my questions."
    yume_th "...ไม่...ไม่ใช่..."
    yume_en "...No... it's not like that..."
    voice "audio/voice/true_end/mary_12_014.mp3"
    mary_th "ฉันสนิทกับเธอมากขึ้นแล้วก็เข้าใจ จริงๆแล้วฉันอยากผูกพันกับเธอตั้งแต่แรกอยู่แล้ว"
    mary_en "The more I got to know you, the more I understood. I wanted to be connected with you from the start."
    yume_th "...ทำไม?"
    yume_en "...Why?"
    voice "audio/voice/true_end/mary_12_015.mp3"
    mary_th "นั่นสินะ อาจเพราะว่าเธอเข้มแข็งกว่าฉันก็ได้"
    mary_en "Perhaps because you are stronger than me."
    yume_th "เข้มแข็ง?"
    yume_en "Strong?"
    th "คำว่า ‘เข้มแข็ง’ เป็นสิ่งที่ไม่เข้ากับตัวเราเลย"
    en "The word 'strong' didn't suit us at all."
    th "คนที่พยายามหลบหนีจากตัวตนของตัวเอง ไม่ว่าจะดูยังไงก็เป็นคนขี้ขลาด"
    en "Someone trying to escape from their own identity, no matter how you look at it, is a coward."


    voice "audio/voice/true_end/mary_12_016.mp3"
    mary_th "ทั้งๆที่เธอมีชีวิตที่โหดร้ายพอกับฉัน แต่เธอเลือกที่จะยืนหยัดกับมัน"
    mary_en "Despite having a life as cruel as mine, you chose to face it."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/true_end/mary_12_017.mp3"
    mary_th "ตอนที่ฉันเห็นเธอยืนขัดโต๊ะคนเดียว โดนคนอื่นรังแกแต่ไม่เคยร้องไห้ ฉันก็คิดมาตลอดว่า ‘เธอคนนี้แหละคือคนที่ฉันอยากเป็น’"
    mary_en "When I saw you standing alone against the table, being bullied by others but never crying, I always thought, 'That's the person I want to be.'"
    th "คำพูดของแมรี่ทำให้เรารู้สึกเจ็บแปลบในอก"
    en "Mary's words pierced our heart with pain."
    th "เธอมองเราเป็นคนเข้มแข็งแบบนั้นมาตลอดเลยงั้นเหรอ"
    en "Was she always seeing us as that strong?"
    voice "audio/voice/true_end/mary_12_018.mp3"
    mary_th "ฉันน่ะเกิดมาร่างกายก็อ่อนแอ พ่อก็ไม่ชอบฉัน แม่ก็ทิ้งฉันไป...เพราะอย่างนั้น ฉันถึงร้องไห้ทุกวัน...ในห้องส่วนตัวที่ไม่มีใครอยู่..."
    mary_en "I was born weak, my father didn't like me, my mother left me... that's why I cried every night... alone in my room."
    yume_th "....."
    yume_en "....."
    th "แมรี่ที่ยิ้มแย้มให้เราร้องไห้ทุกคืน"
    en "The ever-smiling Mary wept every night."
    th "ความจริงที่เราเพิ่งรับรู้ทำให้เรารู้อับอายที่เราไม่เคยเข้าใจเธอ"
    en "The truth we just learned made us feel ashamed for never understanding her."
    th "เราก้มหน้าลงเพื่อหลบสายตาของเธอ แต่แมรี่ช้อนคางของเราขึ้น ให้เราสบตากับเธอตรงๆ"
    en "We lowered our head to avoid her gaze, but Mary lifted our chin to meet her eyes."
    voice "audio/voice/true_end/mary_12_019.mp3"
    mary_th "แต่หลังจากเจอเธอ ฉันก็ร้องไห้น้อยลง"
    mary_en "But after meeting you, I started to cry less."
    voice "audio/voice/true_end/mary_12_020.mp3"
    mary_th "ชีวิตที่มีเธออยู่มันสวยงามมากเลยนะ ยูเมะ...เพราะแบบนั้นฉันเลยแสร้งทำเป็นเข้มแข็งเพื่อให้สามารถยืนร่วมกับเธอได้..."
    mary_en "Life with you in it is so beautiful, Yume... that's why I pretended to be strong, to stand with you..."
    voice "audio/voice/true_end/mary_12_021.mp3"
    mary_th "เพราะอย่างนั้น ฉันเลยไม่ได้บอกความจริงเรื่องร่างกายอ่อนแอให้เธอฟัง เพราะฉันกลัวว่าฉันจะกลายเป็นตัวถ่วงรั้งความเข้มแข็งของเธอ"
    mary_en "That's why I didn't tell you about my physical weakness, afraid that I would become a burden to your strength."

    voice "audio/voice/true_end/mary_12_022.mp3"
    mary_th "...ฉันนี่มันเห็นแก่ตัว...ว่าไหม?"
    mary_en "...I'm so selfish, aren't I?"
    th "เสียงหัวเราะเศร้าๆดังมาจากเด็กสาวผมทอง"
    en "The blonde girl let out a sad laugh."
    th "น้ำตาสองสายของแมรี่หลั่งรินออกมามากขึ้น"
    en "Her tears flowed more freely."
    yume_th "...ไม่หรอก..."
    yume_en "...Not at all..."
    th "เราส่ายหน้าเบาๆ"
    en "We shook our head slightly."
    th "เราไม่ได้เข้มแข็งขนาดนั้นและแมรี่ก็ไม่ใช่คนเห็นแก่ตัว"
    en "We weren't that strong, and Mary wasn't selfish."
    yume_th "ฉันก็อยากอยู่กับเธอเหมือนกัน"
    yume_en "I want to be with you too."
    voice "audio/voice/true_end/mary_12_023.mp3"
    mary_th "...ยูเมะ..."
    mary_en "...Yume..."
    yume_th "ฉันไม่ได้เข้มแข็งอะไรหรอก ฉันแค่ทำเป็นไม่รู้สึกอะไร"
    yume_en "I'm not strong, I just pretended to be numb."
    yume_th "มันง่ายกว่าที่จะปฏิเสธตัวเองและมีชีวิตอยู่ไปวันๆโดยไม่ตั้งคำถาม"
    yume_en "It's easier to deny myself and live day by day without questioning."
    th "ก่อนหน้าที่เราจะเจอแมรี่ เราทิ้งความหวังทั้งหมด เราเลือกที่จะไม่สนใจอะไรทั้งนั้น"
    en "Before meeting Mary, we had given up all hope, choosing to ignore everything."
    th "เราค่อยๆได้ความเป็นมนุษย์กลับมาเมื่อพบกับแมรี่"
    en "We slowly regained our humanity when we met Mary."
    th "ชีวิตของเรามีความหมายขึ้นเมื่อเราได้อยู่กับเธอ"
    en "Our life gained meaning when we were with her."
    yume_th "ฉันต่างหากที่ต้องขอบคุณเธอ ฉันไม่รู้จะชดใช้อะไรให้เธอดี"
    yume_en "It's I who should thank you. I don't know how to repay you."
    yume_th "แต่เมื่อฉันกลับมาพบกับเธอ ฉันก็ไม่มีโอกาสจะทำอะไรเพื่อเธอแล้ว"
    yume_en "But now that I've met you again, I won't have a chance to do anything for you."
    voice "audio/voice/true_end/mary_12_024.mp3"
    mary_th "เธอก็เลย..."
    mary_en "So you..."
    yume_th "ฉันเลยเลือกที่จะทิ้งทุกอย่างอีกครั้ง"
    yume_en "I chose to give up everything again."
    th "เราพูดความจริง"
    en "We spoke the truth."
    th "เรายอมพูดมันออกมาในที่สุด"
    en "We finally admitted it."
    th "ความอ่อนแอของเรา ความเปราะบางของเรา"
    en "Our weakness, our fragility."
    th "...เราไม่สามารถปฏิเสธมันได้อีกต่อไป..."
    en "...We could no longer deny it..."
    yume_th "ขอโทษนะ"
    yume_en "I'm sorry."
    #voice "audio/voice/true_end/mary_12_025.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "ขอโทษที่เป็นคนอ่อนแอ ขอโทษที่เป็นคนขี้ขลาด"
    yume_en "Sorry for being weak, for being a coward."
    #voice "audio/voice/true_end/mary_12_026.mp3"
    mary_th "....."
    mary_en "....."
    yume_th "ขอโทษที่ทำให้เธอมีความสุขไม่ได้เลย"
    yume_en "Sorry for not being able to make you happy."
    th "คำพูดของเราถูกหยุดลงเพราะอ้อมกอดของแมรี่แน่นหนาขึ้น"
    en "Our words were stopped by Mary's tightening embrace."
    th "สองแขนบางที่โอบร่างเราไว้สั่นเทาไปหมด"
    en "Her thin arms shaking as they held us."
    voice "audio/voice/true_end/mary_12_027.mp3"
    mary_th "นั่นมันไม่จริงสักหน่อย"
    mary_en "That's not true at all."
    yume_th "....."
    yume_en "....."
    voice "audio/voice/true_end/mary_12_028.mp3"
    mary_th "ช่วงเวลาที่เธออยู่กับฉัน ฉันมีความสุขที่สุดเลยนะ"
    mary_en "The times I spent with you were the happiest."
    yume_th "แมรี่"
    yume_en "Mary"
    voice "audio/voice/true_end/mary_12_029.mp3"
    mary_th "เพราะฉะนั้น ฉันจะไม่ยอมให้ชีวิตของเธอจบลงแค่นี้"
    mary_en "That's why I won't let your life end here."


    th "ดวงตาของแมรี่แน่วแน่"
    en "Mary's eyes were resolute."
    th "แม้น้ำตาจะยังอาบท่วมนวลแก้มขาว แต่ความปรารถนาอันแรงกล้าของเธอไม่มีวันสั่นคลอน"
    en "Even as tears flooded her pale cheeks, her strong desire never wavered."
    voice "audio/voice/true_end/mary_12_030.mp3"
    mary_th "ชีวิตมันอาจจะไม่ยุติธรรมและโหดร้าย แต่นั่นไม่ใช่ทั้งหมดหรอกนะ"
    mary_en "Life may be unfair and cruel, but that's not everything."
    voice "audio/voice/true_end/mary_12_031.mp3"
    mary_th "เพราะเธอมีชีวิตอยู่ พวกเราเลยมีโอกาสได้เจอกัน...จริงไหมล่ะ?"
    mary_en "Because you're alive, we had the chance to meet... right?"
    th "คำพูดของแมรี่หลั่งไหลเข้ามาในใจเรา เราไม่สามารถปฏิเสธเธอได้"
    en "Mary's words flowed into our heart. We couldn't deny her."
    th "เราคือคนขี้ขลาด เธอต่างหากที่เป็นคนเข้มแข็ง"
    en "We were the cowards. She was the strong one."
    th "ไม่งั้นเธอคงไม่ทุ่มเทพาเราเดินมาถึงห้องสุดท้ายเพื่อพาเรากลับมาหรอก"
    en "Otherwise, she wouldn't have brought us all the way to this final room to bring us back."
    voice "audio/voice/true_end/mary_12_032.mp3"
    mary_th "ถ้าตายไปแล้ว มันไม่มีความทุกข์ก็จริงแต่ความสุขทั้งหมดก็จะหายไปเหมือนกัน"
    mary_en "If you die, yes, there's no suffering, but all happiness is gone too."
    voice "audio/voice/true_end/mary_12_033.mp3"
    mary_th "ตราบใดที่ยังมีชีวิต เธอก็ยังมีโอกาส ตราบใดที่ยังมีโอกาส เธอก็ยังสามารถมีความสุขได้"
    mary_en "As long as you're alive, you have a chance. As long as there's a chance, you can find happiness."
    yume_th "...ความสุข...ในโลกที่ไม่มีเธองั้นเหรอ...?"
    yume_en "...Happiness... in a world without you...?"
    th "เราพูดแทรกขึ้นด้วยเสียงสะอื้นไห้"
    en "I interjected with a sobbing voice."
    th "เด็กสาวผมทองพยักหน้าให้เราพร้อมกับยื่นมือข้างหนึ่งมาสัมผัสแก้มขวาเราไว้"
    en "The blonde girl nodded at us, reaching out to touch our right cheek."
    voice "audio/voice/true_end/mary_12_034.mp3"
    mary_th "ฉันไม่ใช่ตัวแทนความสุขของเธอ"
    mary_en "I'm not the embodiment of your happiness."
    voice "audio/voice/true_end/mary_12_035.mp3"
    mary_th "โลกนี้ยังมีอีกหลายสิ่งที่ทำให้เธอมีความสุขได้"
    mary_en "There are many things in this world that can make you happy."
    voice "audio/voice/true_end/mary_12_036.mp3"
    mary_th "เพราะฉะนั้น จงมีชีวิตอยู่ต่อไปซะ ยูเมะ"
    mary_en "So live on, Yume."
    voice "audio/voice/true_end/mary_12_037.mp3"
    mary_th "จงมีชีวิตและมีความสุข"
    mary_en "So live on, Yume."
    voice "audio/voice/true_end/mary_12_038.mp3"
    mary_th "และหลังจากใช้ชีวิตเต็มที่แล้วค่อยรักษาสัญญาที่มีต่อฉันก็ยังไม่สาย"
    mary_en "And after living your life to the fullest, it's not too late to keep your promise to me."
    voice "audio/voice/true_end/mary_12_039.mp3"
    mary_th "...เข้าใจนะ"
    mary_en "...Understand?"
    yume_th "...พวกเราจะกลับมาพบกันอีกครั้ง..."
    yume_en "...We will meet again..."
    voice "audio/voice/true_end/mary_12_040.mp3"
    mary_th "ใช่แล้วจ้ะ"
    mary_en "Yes, indeed."
    th "แมรี่ยิ้มกว้างขึ้นทั้งน้ำตา"
    en "Mary smiled through her tears"
    th "นี่สินะ คือความปรารถนาที่แท้จริงของเธอ"
    en "So, this is your true wish."
    th "...เธออยากให้เรามีชีวิตอยู่..."
    en "...You want me to live..."
    th "...เธออยากให้เราพบกับความสุขโดยที่เป็นอิสระจากตัวเธอ..."
    en "...You want me to find happiness, free from you..."

    yume_th "แมรี่"
    yume_en "Mary"
    voice "audio/voice/true_end/mary_12_041.mp3"
    mary_th "จ้ะ?"
    mary_en "Yes?"
    yume_th "เธอนี่มัน...เห็นแก่ตัวจริงๆ..."
    yume_en "You are... really selfish..."
    th "คำพูดของเราสิ้นสุดลง สัมผัสอบอุ่นก็ประทับลงบนริมฝีปากของเรา"
    en "Our words ended, and a warm touch pressed against our lips."
    th "จุมพิตที่หอมหวานและเต็มไปด้วยความเจ็บปวดเชื่อมต่อพวกเราสองคนเอาไว้"
    en "The kiss, sweet and filled with pain, connected the two of us."
    th "ก่อนที่ใบหน้าของพวกเราทั้งสองจะเลื่อนห่างออกจากกัน"
    en "Before our faces slowly moved apart from each other."
    voice "audio/voice/true_end/mary_12_042.mp3"
    mary_th "ขอโทษและขอบคุณสำหรับทุกสิ่งทุกอย่างนะจ้ะ"
    mary_en "I'm sorry and thank you for everything."
    yume_th "...แมรี่..."
    yume_en "...Mary..."
    voice "audio/voice/true_end/mary_12_043.mp3"
    mary_th "ลาก่อน ผู้หญิงที่ฉันรักที่สุดในโลก"
    mary_en "Goodbye, the woman I love most in this world."
    scene white with Dissolve(5)
    th "โลกรอบข้างถูกแสงสีขาวกลืนกินเข้าไปทีละน้อยๆ"
    en "The world around us was slowly swallowed by white light."
    th "แสงสว่างอันอบอุ่นค่อยๆปกคลุมทัศนียภาพตรงหน้า"
    en "The warm light gradually covered the scene before us."
    th "สิ่งสุดท้ายที่เราเห็นก่อนที่สีขาวบริสุทธิ์จะดูดกลืนเราเข้าไปคือรอยยิ้ม"
    en "The last thing we saw before the pure white engulfed us was a smile."
    th "...รอยยิ้มของแมรี่..."
    en "...Mary's smile..."
    yume_th "ลาก่อน แมรี่"
    yume_en "Goodbye, Mary."

###############################################################
    scene black with Dissolve(5)
    
    stop music
    play music アクアの旅路

    th "คฤหาสน์แห่งนั้นคงเป็นโลกระหว่างความเป็นความตาย"
    en "That mansion must have been a world between life and death."
    th "เราจงใจฆ่าตัวตายเพื่อจะตามแมรี่ไป แต่แมรี่ก็พยายามทุกวิถีทางเพื่อดึงตัวตนเรากลับมาและพาชีวิตที่ใกล้แหลกสลายของเรากลับมายังโลกของคนเป็น"
    en "I intentionally took my own life to follow Mary, but she tried everything to bring my nearly shattered existence back to the world of the living."
    th "....."
    en "....."
    scene hospital with dissolve 
    th "หลังจากลากับแมรี่ เราลืมตาตื่นขึ้นและพบตัวเองนอนอยู่ในโรงพยาบาล"
    en "After saying goodbye to Mary, I woke up to find myself in a hospital."
    th "แพทย์ที่ดูแลเราบอกเราว่าเราพ้นภาวะวิกฤติอย่างฉิวเฉียด"
    en "The doctor told me that I narrowly escaped a critical condition."
    th "ปาฏิหาริย์ ทุกคนขนานนามการรอดชีวิตของเราแบบนั้น"
    en "A miracle - that's what everyone called my survival."
    th "...มันก็คงไม่ผิดจริงๆ..."
    en "...And it wasn't wrong..."
    th "แมรี่คือปาฏิหาริย์ของเราเสมอมา"
    en "Mary has always been my miracle."
    th "....."
    en "....."
    scene sky_morning with dissolve
    th "ตั้งแต่แมรี่เสียชีวิต เวลาก็ผ่านมาหลายปีแล้ว"
    en "Years have passed since Mary's death."

    
    yume_th "ฉันมาเยี่ยมเธอนะ แมรี่"
    yume_en "Yume: I've come to visit you, Mary."
    scene cg3 with Dissolve(1)

    th "วันนี้คือวันครบรอบวันตายของเธอ" 
    en "Today marks the anniversary of her death."
    th "เรามาเยี่ยมเธอพร้อมกับดอกไม้ที่เธอชอบที่สุด"
    en "I visited her grave with her favorite flowers in hand"
    yume_th "ฉันจำได้ เธอชอบดอกพลับพลึงขาวใช่ไหมล่ะ?"
    yume_en "I remember, you liked white balloon flowers, didn't you?"
    th "เราพูดพร้อมกับวางดอกไม้หน้าสุสานของผู้หญิงที่ตัวเองรัก แม้เราจะรู้แก่ใจว่าแมรี่ไม่อยู่กับเราแล้ว แต่เราก็ยังคุยกับป้ายสุสานเหมือนเธอยังมีชีวิตอยู่"
    en "I spoke as I placed the flowers at the tombstone of the woman I loved, talking to the grave marker as if she were still alive."
    th "เราจ้องมองป้ายสุสานตรงหน้าด้วยรอยยิ้มเศร้าๆ"
    en "I gazed at the tombstone with a sad smile."
    th "อดีตที่แสนขมขื่นทำให้เราเจ็บปวดทุกครั้งที่นึกถึง แต่มันไม่มีทางทำให้เราอ่อนแอลงหรือพยายามปฏิเสธตัวเองอีกครั้ง"
    en "The bitter past hurts every time I think of it, but it will not make me weak or deny myself again."
    th "...แมรี่คือคนที่ทำให้เราเข้าใจถึงคุณค่าของชีวิต..."
    en "...Mary taught me the value of life..."
    th "ไม่ว่าจะเป็นความทุกข์ ความสุข การสูญเสียหรือความเจ็บปวด"
    en "Be it suffering, joy, loss, or pain."
    th "ทุกสิ่งล้วนหล่อหลอมให้เรากลายเป็นเราจนถึงทุกวันนี้"
    en "All these shaped me into who I am today."
    th "....."
    en "....."
    th "จริงอยู่ที่อดีตทำให้เราเจ็บปวด แต่เราก็ขอมีชีวิตอยู่กับมันอย่างภาคภูมิ"
    en "It's true the past pains me, but I choose to live with it with dignity."
    th "เราจะไม่ปฏิเสธตัวเองอีกต่อไป"
    en "I will not deny myself any longer."
    th "....."
    en "....."
    th "เราคุกเข่าลงต่อหน้าสุสานของแมรี่"
    en "I knelt in front of Mary's grave."
    yume_th "คนเห็นแก่ตัว"
    yume_en "Selfish person."
    yume_th "เพราะเธอแท้ๆเลย ฉันเลยต้องมีชีวิตอยู่ต่อไป"
    yume_en "It's all because of you that I have to keep living."
    yume_th "ฮะๆๆ"
    yume_en "Ha ha ha."
    th "เราหัวเราะ"
    en "I laughed."
    th "มันไม่ใช่เสียงหัวเราะประชดประชัน แต่เป็นเสียงหัวเราะจากใจจริงของเรา"
    en "It wasn't a laugh of irony but a genuine one from the heart."
    th "แทนที่จะจมปลักกับความเศร้าจากการสูญเสียคนสำคัญ สู้จดจำช่วงเวลาอันสวยงามที่เราได้ใช้ชีวิตร่วมกับคนคนนั้นเสียยังจะดีกว่า"
    en "Instead of dwelling on the sadness of losing someone important, it's better to remember the beautiful moments spent together."
    th "....."
    en "....."
    scene sky_morning with dissolve
    th "เราเงยหน้าขึ้นมองท้องฟ้า"
    en "I looked up at the sky."
    th "ท้องฟ้าปลอดโปร่ง"
    en "The sky was clear."
    th "...ช่างเป็นวันที่สวยงามจริงๆ..."
    en "...Such a beautiful day.."
    th "...เพราะเรายังมีชีวิตอยู่ เราเลยได้เห็นท้องฟ้านี้..."
    en "...Because I am alive, I get to see this sky..."
    th "...ตราบใดที่ยังมีลมหายใจ เราก็ยังมีโอกาสที่จะมีความสุข..."
    en "...As long as I breathe, I have the chance to be happy..."
    th "....."
    en "....."
    th "...ใช่ไหมล่ะ...แมรี่ของฉัน..."
    en "...Right... my Mary..."
    $ persistent.true_end_pass = True
    scene white with Dissolve(3)
    scene meandmary with Dissolve(3)
    scene black with Dissolve(5)
    return
